spring.application.name=Project-Management-System
spring.datasource.url=jdbc:postgresql://localhost:5432/project_management
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}